Fix misleading indentation warning:
usr.sbin/lmcconfig/lmcconfig.c:941:39: error: misleading indentation; statement is not part of the previous 'if' [-Werror,-Wmisleading-indentation]
                                      return 64.0;
                                      ^
usr.sbin/lmcconfig/lmcconfig.c:940:3: note: previous statement is here
  if ((vga >= 0x3A) && (vga <  0x3F)) return 50.0 + 2.80 * (vga - 0x3A);
  ^

Direct commit to stable/11, since lmcconfig has been removed from
FreeBSD 12 and later.