Fix unused variable warning in netipsec's key_debug.c
With clang 15, the following -Werror warning is produced:

    sys/netipsec/key_debug.c:923:9: error: variable 'j' set but not used [-Werror,-Wunused-but-set-variable]
            int i, j;
                   ^

The 'j' variable was in key_debug.c when it was first added, but it
appears to have been a debugging aid that has never been used, so remove
it.

MFC after:	3 days

(cherry picked from commit c01fdd7a9f316c8c04786441ca0113be002b96be)