Fix misleading indentation warning:
sys/dev/nxge/xgehal/xgehal-mgmt.c:1743:6: error: misleading indentation; statement is not part of the previous 'if' [-Werror,-Wmisleading-indentation]
            addr = 0xA074;
            ^
sys/dev/nxge/xgehal/xgehal-mgmt.c:1736:2: note: previous statement is here
        if(CHECKBIT(val_1, 0x0))
        ^

Direct commit to stable/11, since nxge(4) has been removed from FreeBSD
12 and later.