moused: fix GCC build
error: 'static' is not at beginning of declaration [-Werror=old-style-declaration]

(cherry picked from commit 54cc3da443da7e4a8a483d1fe46071382ff06ed0)